# Generated by Django 5.2.7 on 2025-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_car_driver_eventtype_mcaplog_notes_mcaplog_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text='List of channel names'),
        ),
        migrations.AddField(
            model_name='mcaplog',
            name='end_time',
            field=models.FloatField(help_text='Unix timestamp in seconds', null=True),
        ),
        migrations.AddField(
            model_name='mcaplog',
            name='start_time',
            field=models.FloatField(help_text='Unix timestamp in seconds', null=True),
        ),
    ]
