# Generated by Django 5.2.7 on 2025-11-12 18:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mcaplog_channels_mcaplog_end_time_mcaplog_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='GPS location (latitude, longitude)', null=True, srid=4326),
        ),
    ]
