# Generated by Django 5.2.7 on 2025-11-12 22:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mcaplog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='lap_path',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, help_text='GPS path as LineString for map preview', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mcaplog',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='User-tagged location point (can be manually set or auto-extracted from lap_path in the future)', null=True, srid=4326),
        ),
    ]
