# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mcaplog_parse_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='User-defined tags for filtering (e.g. bell crank testing, other test)'),
        ),
    ]
