# Generated by Django 5.2.7 on 2026-02-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mcaplog_freeform_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcaplog',
            name='car',
        ),
        migrations.RemoveField(
            model_name='mcaplog',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='mcaplog',
            name='event_type',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
