# Generated by Django 5.2.7 on 2026-02-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_mcaplog_car_remove_mcaplog_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaplog',
            name='map_preview_uri',
            field=models.CharField(blank=True, help_text='Immutable SVG map preview URI', max_length=500, null=True),
        ),
    ]
