"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
for env_path in (BASE_DIR / ".env", BASE_DIR.parent / ".env"):
    if env_path.exists():
        environ.Env.read_env(str(env_path))

# GeoDjango library paths (for macOS with Homebrew)
# Try to find GDAL library automatically, fallback to common paths
gdal_paths = [
    "/opt/homebrew/lib/libgdal.dylib",  # Symlink (preferred)
    "/opt/homebrew/lib/libgdal.37.dylib",  # Versioned
    "/usr/local/lib/libgdal.dylib",  # Intel Mac
]
GDAL_LIBRARY_PATH = os.environ.get("GDAL_LIBRARY_PATH") or next(
    (p for p in gdal_paths if os.path.exists(p)), "/opt/homebrew/lib/libgdal.dylib"
)

geos_paths = [
    "/opt/homebrew/lib/libgeos_c.dylib",
    "/usr/local/lib/libgeos_c.dylib",
]
GEOS_LIBRARY_PATH = os.environ.get("GEOS_LIBRARY_PATH") or next(
    (p for p in geos_paths if os.path.exists(p)), "/opt/homebrew/lib/libgeos_c.dylib"
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-p^(ga6^d1p2c#(&@hl5pz0#$7by@0n8jy9nka(md%o)qrg_80h",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

_allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "").strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    # Dev-friendly defaults (Docker + local)
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",  # GeoDjango for PostGIS
    "rest_framework",
    "corsheaders",
    "drf_yasg",  # Swagger/OpenAPI documentation
    "channels",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware should be as high as possible
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"
ASGI_APPLICATION = "backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

POSTGRES_DB = os.environ.get("POSTGRES_DB", "mcap_query_db")
POSTGRES_USER = os.environ.get("POSTGRES_USER", "postgres")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", "postgres")
# For local dev we map Postgres to localhost:5433; for Docker use service name "db" on 5432.
POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "localhost")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT", "5433")
_database_url_default = f"postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

DATABASES = {"default": env.db("DATABASE_URL", default=_database_url_default)}
DATABASES["default"]["ENGINE"] = "django.contrib.gis.db.backends.postgis"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", "/Users/pettruskonnoth/Documents"))
_mcap_logs_dir_env = os.environ.get("MCAP_LOGS_DIR", "").strip()
if _mcap_logs_dir_env:
    _candidate_logs_dir = Path(_mcap_logs_dir_env)
    MCAP_LOGS_DIR = (
        _candidate_logs_dir
        if _candidate_logs_dir.is_absolute()
        else MEDIA_ROOT / _candidate_logs_dir
    )
else:
    _mcap_logs_subdir = os.environ.get("MCAP_LOGS_SUBDIR", "mcap_logs").strip(" /")
    if not _mcap_logs_subdir:
        _mcap_logs_subdir = "mcap_logs"
    MCAP_LOGS_DIR = MEDIA_ROOT / _mcap_logs_subdir

try:
    _relative_logs_dir = MCAP_LOGS_DIR.resolve().relative_to(MEDIA_ROOT.resolve())
    MCAP_LOGS_URI_PREFIX = f"{MEDIA_URL.rstrip('/')}/{_relative_logs_dir.as_posix()}"
except ValueError:
    # If MCAP_LOGS_DIR is outside MEDIA_ROOT, keep a stable URI prefix.
    MCAP_LOGS_URI_PREFIX = f"{MEDIA_URL.rstrip('/')}/mcap_logs"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
_cors_allowed_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS", "").strip()
if _cors_allowed_origins_env:
    CORS_ALLOWED_ORIGINS = [
        o.strip() for o in _cors_allowed_origins_env.split(",") if o.strip()
    ]
else:
    frontend_port = os.environ.get("FRONTEND_PORT", "3000")
    CORS_ALLOWED_ORIGINS = [
        f"http://localhost:{frontend_port}",
        f"http://127.0.0.1:{frontend_port}",
    ]

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)

# Allow all headers
CORS_ALLOW_ALL_HEADERS = True

# Allow common HTTP methods
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# drf-yasg (Swagger/OpenAPI) settings
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {"Basic": {"type": "basic"}},
    "USE_SESSION_AUTH": False,
}

REDOC_SETTINGS = {
    "LAZY_RENDERING": False,
}

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # Number of items per page
}

# Celery Configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)

CHANNEL_REDIS_URL = env("CHANNEL_REDIS_URL", default=CELERY_BROKER_URL)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
        },
    }
}

# Celery task settings
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# Map preview generation
MAP_PREVIEW_TILE_URL_TEMPLATE = os.environ.get(
    "MAP_PREVIEW_TILE_URL_TEMPLATE", "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
)
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Task execution settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Conversion defaults
MOTEC_RESAMPLE_HZ_DEFAULT = float(os.environ.get("MOTEC_RESAMPLE_HZ_DEFAULT", "20.0"))
